#ifndef CONFIGURATION_H_INCLUDED
#define CONFIGURATION_H_INCLUDED

#define WINDOW_WIDTH (1024)
#define WINDOW_HEIGHT (768)

#define TITLE_APPLICATION "Mon premier jeu vidéo"

#define PRET 0.1
#define LOIN 1000.0
#define ANGLE_VISION 70.0


#endif // CONFIGURATION_H_INCLUDED
